CREATE TABLE b_awz_utm (
    ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PARENT_ID int DEFAULT NULL,
    SITE_ID varchar(2) DEFAULT NULL,
    IP_ADDR varchar(45) DEFAULT NULL,
    U_AGENT varchar(255) DEFAULT NULL,
    REFERER varchar(255) DEFAULT NULL,
    "SOURCE" varchar(25) DEFAULT NULL,
    MEDIUM varchar(25) DEFAULT NULL,
    CAMPAIGN varchar(25) DEFAULT NULL,
    CONTENT varchar(25) DEFAULT NULL,
    TERM varchar(25) DEFAULT NULL,
    DATE_ADD datetime DEFAULT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX b_awz_utm_site_id ON b_awz_utm (site_id);
CREATE INDEX b_awz_utm_date_add ON b_awz_utm (date_add);